/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import coordinador.Coordinador;
import coordinador.Conector;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Ángel
 */
public class guiConsulta extends javax.swing.JFrame {

    /**
     * Creates new form guiConsulta
     */
    public guiConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UsuarioConsulta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BTNCONSULTAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resConsulta = new javax.swing.JTextArea();
        BTNVOLVERCONS = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consulta:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        UsuarioConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(UsuarioConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 59, 198, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número de usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 59, -1, -1));

        BTNCONSULTAR.setText("Consultar");
        BTNCONSULTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCONSULTARActionPerformed(evt);
            }
        });
        jPanel1.add(BTNCONSULTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 91, -1, -1));

        resConsulta.setColumns(20);
        resConsulta.setRows(5);
        jScrollPane1.setViewportView(resConsulta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 135, 380, -1));

        BTNVOLVERCONS.setText("Volver");
        BTNVOLVERCONS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVOLVERCONSActionPerformed(evt);
            }
        });
        jPanel1.add(BTNVOLVERCONS, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 245, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/fondo.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 420, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNVOLVERCONSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVOLVERCONSActionPerformed
        guiCoord guiCoordi = new guiCoord();
        guiCoordi.setVisible(true);
        guiCoordi.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BTNVOLVERCONSActionPerformed

    private void BTNCONSULTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCONSULTARActionPerformed
        Conector cliente = new Conector();
        String numusuario = UsuarioConsulta.getText();
        String cta = null;
        cliente.conectar('C');
        try {
            cta = cliente.consulta(numusuario);
        } catch (SQLException ex) {
            Logger.getLogger(guiConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }
        String estadoCta ="Estado de la Cuenta:\n"+ cta;
        JOptionPane.showMessageDialog(null,estadoCta);
        resConsulta.setText(estadoCta);
    }//GEN-LAST:event_BTNCONSULTARActionPerformed

    private void UsuarioConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioConsultaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCONSULTAR;
    private javax.swing.JButton BTNVOLVERCONS;
    private javax.swing.JTextField UsuarioConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resConsulta;
    // End of variables declaration//GEN-END:variables
}
