/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import coordinador.Conector;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Ángel
 */
public class guiCoord extends javax.swing.JFrame {

    /**
     * Creates new form guiCoord
     */
    public guiCoord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTNDEPOSITO = new javax.swing.JButton();
        BTNRETIRO = new javax.swing.JButton();
        BTNCONSULTA = new javax.swing.JButton();
        BTNSALIR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione la operación que desee realizar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        BTNDEPOSITO.setText("Deposito");
        BTNDEPOSITO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDEPOSITOActionPerformed(evt);
            }
        });
        jPanel1.add(BTNDEPOSITO, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 133, -1, -1));

        BTNRETIRO.setText("Retiro");
        BTNRETIRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRETIROActionPerformed(evt);
            }
        });
        jPanel1.add(BTNRETIRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 177, 84, -1));

        BTNCONSULTA.setText("Consulta");
        BTNCONSULTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCONSULTAActionPerformed(evt);
            }
        });
        jPanel1.add(BTNCONSULTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 89, -1, -1));

        BTNSALIR.setText("Salir");
        BTNSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSALIRActionPerformed(evt);
            }
        });
        jPanel1.add(BTNSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 221, 84, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/fondo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNDEPOSITOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDEPOSITOActionPerformed
        guiDeposito guiDep = new guiDeposito();
        guiDep.setVisible(true);
        guiDep.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BTNDEPOSITOActionPerformed

    private void BTNRETIROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRETIROActionPerformed
        guiretirar guiRet = new guiretirar();
        guiRet.setVisible(true);
        guiRet.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BTNRETIROActionPerformed

    private void BTNCONSULTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCONSULTAActionPerformed
        guiConsulta guiCons = new guiConsulta();
        guiCons.setVisible(true);
        guiCons.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BTNCONSULTAActionPerformed

    private void BTNSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSALIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BTNSALIRActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCONSULTA;
    private javax.swing.JButton BTNDEPOSITO;
    private javax.swing.JButton BTNRETIRO;
    private javax.swing.JButton BTNSALIR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
